spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: gateway
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
server:
  port: 9000
  max-http-header-size: 104857600
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
