spring:
    cloud:
      gateway:
          httpclient:
              response-timeout: 60000 # 设置为60秒
              response-buffer-size: 64MB # 响应缓存区大小，单位为字节
    main:
        allow-bean-definition-overriding: true
    application:
        name: gateway
    servlet:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB
server:
    port: 9000
    max-http-header-size: 104857600
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/
ribbon:
    ConnectTimeot: 100000 # 连接超时时间（ms）
    ReadTimeot: 100000 # 通信超时时间（ms）
    SocketTimeout: 100000
    OkToRertryOnAllOperations: ture # 是否对所有操作重试
    MaxAutoRetriesNextServer: 1 #同一个服务不同实例的重试次数
    MaxAutoRetries: 1 #同一实例的重试次数
    RetryableStatusCodes: 500, 502, 503, 504 # 指定可以进行重试的HTTP状态码
    eager-load:
        enabled: true
feign:
    hystrix:
        enabled: true # 启用Feign的Hystrix支持
    client:
        config:
            default:
                connectTimeout: 100000 # 连接超时时间
                readTimeout: 100000 # 读取超时时间
hystrix:
    command:
        default:
            execution:
                timeout:
                    enabled: false
                isolation:
                    thread:
                        timeoutInMilliseconds: 300000

zuul:
    servlet:
        max-request-size: 100MB
        max-file-size: 100MB
    host:
        connect-timeout-millis: 1000000
        socket-timeout-millis: 1000000
    thread-pool:
        use-global-thread-pool: true # 是否使用全局线程池
        thread-name-prefix: zuulThreadPool # 线程名称前缀
        core-size: 10 # 核心线程数
        max-size: 100 # 最大线程数
        queue-size: 1000 # 等待队列大小
logging:
    level:
        org.springframework.cloud.gateway: DEBUG